name: "🔧 Refactor"
description: "리팩토링 사항"
labels: ["🔧 Refactor"]
title: " [REFACTOR] "
body:
  - type: textarea
    id: overview
    attributes:
      label: 📌 개요
      description: 리팩토링이 필요한 이유와 주요 목표를 간략히 설명해 주세요.
      placeholder: ex. 클래스 간 결합도가 높아 유지보수가 어려움
    validations:
      required: true
  - type: textarea
    id: changes
    attributes:
      label: 🎯 변경 내용
      description: 어떤 부분을 어떻게 리팩토링할 것인지 구체적으로 기술해 주세요.
      placeholder: ex. A 모듈과 B 모듈의 의존성을 분리합니다.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: ✅ 체크리스트
      options:
        - label: 코드 가독성 향상
        - label: 중복 코드 제거
        - label: 성능 개선
        - label: 테스트 코드 수정 및 추가
        - label: 기타 (추가 내용 입력)
  - type: textarea
    attributes:
      label: 📂 관련 파일
      description: 리팩토링 대상이 되는 주요 파일 목록을 작성해 주세요.
      placeholder: ex. /src/components/Button.tsx
  - type: textarea
    attributes:
      label: 📝 참고 사항
      description: 추가적으로 공유하거나 논의하고 싶은 내용을 작성해 주세요.
