name: "✅ Test"
description: "새로운 기능 추가"
labels: ["✅ Test"]
title: " [TEST] "
body:
  - type: textarea
    attributes:
      label: 📌 개요
      description: 테스트가 필요한 이유와 주요 목표를 간략히 설명해 주세요.
      placeholder: ex. 신규 기능에 대한 테스트 필요
  - type: textarea
    attributes:
      label: 🎯 테스트 대상
      description: 어떤 기능, 모듈, 컴포넌트를 테스트할 것인지 기재해 주세요.
      placeholder: ex. 로그인 모듈, 유저 컴포넌트 등
  - type: textarea
    attributes:
      label: 🔍 테스트 시나리오
      description: 테스트 항목을 마크다운 형식으로 자유롭게 편집할 수 있습니다.
      placeholder: |
        1. **[기능/컴포넌트명]**
           - [ ] 입력값 A를 제공했을 때 결과 B가 나오는지 확인
           - [ ] 경계값 테스트 (예: 최소값, 최대값)
           - [ ] 예외 처리 테스트

        2. **[API 테스트]**
           - [ ] 정상 요청 시 200 OK 응답
           - [ ] 잘못된 요청 시 적절한 에러 코드 반환

        3. **[UI 테스트]**
           - [ ] 버튼 클릭 시 올바른 동작 수행
           - [ ] 화면 요소가 정상적으로 렌더링
  - type: checkboxes
    attributes:
      label: ✅ 체크리스트
      options:
        - label: 단위 테스트 (Unit Test)
        - label: 통합 테스트 (Integration Test)
        - label: E2E 테스트 (End-to-End Test)
        - label: 성능 테스트 (Performance Test)
        - label: 기타 (추가 테스트 필요 시 기재)
  - type: textarea
    attributes:
      label: 📂 관련 파일 / 테스트 코드 위치
      description: 테스트 코드가 작성될 파일 경로 또는 위치를 명시해 주세요.
      placeholder: ex. /tests/Login.test.tsx
  - type: textarea
    attributes:
      label: 📝 참고 사항
      description: 추가적으로 공유하거나 논의하고 싶은 내용을 작성해 주세요.
